### ISSUE TITLE
Excuse me,I have a question about main.py 

### ISSUE THREAD

**Issue by Aithusa1113** [kunalrdeshmukh/Image_Compression#2]
in your main.py line 96
    encoder_output = encoder(input)
    decoder_output, residual_img, upscaled_image  = decoder(input)
why does encoder_output never used

**Comment by kunalrdeshmukh** [comment]
Thank you so much !! 
And i was wondering all the while why its not working !!!  It should be 'encoded_output' as an input to decoder.  I will push a new version tomorrow.
